name: GTags
version: ${project.version}
main: net.nifheim.gtags.Gtags
api-version: 1.13
database: true
depend:
- CommandLib
- CoreUtils
softdepend:
- Matrix
libraries:
- com.zaxxer:HikariCP:5.0.0
- org.mariadb.jdbc:mariadb-java-client:2.7.3
- com.github.ben-manes.caffeine:caffeine:3.0.2
